lista_initiala = [7, 8, 9, 2, 3, 1, 4, 10, 5, 6 ]
print(f'Lista intitiala este: {lista_initiala}')
crescator = lista_initiala.copy()
crescator.sort()
print(f"Lista aranjata ascendent: {crescator}")
descrescator = lista_initiala.copy()
descrescator.sort(reverse=True)
print(f"Lista ananjata descrescator: {descrescator}")
nr_pare = slice(1, -1, 2)
print(f"Numerele pare din lista sunt: {crescator[nr_pare]}")
nr_impare = slice(0, -1, 2)
print(f"Numerele impare din lista sunt: {crescator[nr_impare]}")
multipli_de_3 = slice(2, -1, 3)
print(f"Multiplii de 3 din lista sunt: {crescator[multipli_de_3]}")